name: my_global_tools
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0
  dio: ^5.2.1+1
  ansicolor: ^2.0.1
  connectivity_plus: ^4.0.1
  fluttertoast: ^8.2.2
  provider: ^6.0.5
  awesome_snackbar_content: ^0.1.3
  cherry_toast: ^1.3.1
  google_fonts: ^5.1.0
  flutter_dropdown_alert: ^1.0.7
  animated_toast_list: ^1.0.2
  elegant_notification: ^1.10.1
  url_launcher: ^6.1.12
  flutter_linkify: ^6.0.0
  quickalert: ^1.0.1
  material_dialogs: ^1.1.4
  lottie: ^2.4.0
  panara_dialogs: ^0.1.4
  fluid_dialog: ^2.0.0
  animations: ^2.0.7
  flutter_beautiful_popup: ^1.7.0
  flutter_highlight: ^0.7.0
  flutter_colorpicker: ^1.0.3
  rive: ^0.7.16
  flutter_cache_manager: ^3.3.1
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  permission_handler: ^10.4.3
  api_cache_manager: ^1.0.2
  get_it: ^7.6.0
  intl: ^0.18.0
  html: ^0.15.4
  package_info_plus: ^4.0.2
  go_router: ^9.0.3
  get: ^4.6.5
  webview_flutter: ^4.2.2
  uni_links: ^0.5.1
  dev: ^1.0.0
  font_awesome_flutter: ^10.5.0
  flutter_localizations:
    sdk: flutter
  simple_horizontal_stepper: ^0.0.1
  hexcolor: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0



flutter:


  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/designs/
    - assets/svgs/
    - assets/images/
    - assets/videos/
    - assets/rive/
    - assets/lottie/
    - assets/gif/
    - icons/


    #translation
    - assets/translations/

  fonts:
    - family: halter
      fonts:
        - asset: fonts/halter.ttf